import envi.archs.ppc.regs as eapr

INTC_STATE_NORMAL = 0
INTC_STATE_NONCRIT = 1
INTC_STATE_GUEST = 2
INTC_STATE_CRIT = 3
INTC_STATE_DEBUG = 4
INTC_STATE_MACHINECHECK = 5

EXC_RESET               = None
EXC_CRITICAL_INPUT      = eapr.REG_IVOR0
EXC_MACHINE_CHECK       = eapr.REG_IVOR1
EXC_MACHINE_CHECK_NMI   = eapr.REG_IVOR1
EXC_DATA_STORAGE        = eapr.REG_IVOR2
EXC_INSTR_STORAGE       = eapr.REG_IVOR3
EXC_EXTERNAL_INPUT      = eapr.REG_IVOR4
EXC_ALIGNMENT           = eapr.REG_IVOR5
EXC_PROGRAM             = eapr.REG_IVOR6
EXC_FLOAT_UNAVAILABLE   = eapr.REG_IVOR7
EXC_SYSTEM_CALL         = eapr.REG_IVOR8
EXC_AP_UNAVAILABLE      = eapr.REG_IVOR9
EXC_DECREMENTER         = eapr.REG_IVOR10
EXC_FIXED_TIMER_INTERVAL= eapr.REG_IVOR11
EXC_WATCHDOG_TIMER      = eapr.REG_IVOR12
EXC_DATA_TLB_ERROR      = eapr.REG_IVOR13
EXC_INSTR_TLB_ERROR     = eapr.REG_IVOR14
EXC_DEBUG               = eapr.REG_IVOR15
# 16-31 are reserved
EXC_SPE_EFPU_UNAVAILABLE= eapr.REG_IVOR32
EXC_EFPU_DATA           = eapr.REG_IVOR33
EXC_EFPU_ROUND          = eapr.REG_IVOR34
EXC_PERFORMANCE         = eapr.REG_IVOR35

# Following IVOR registers not supported on the current target

# E.PC (embedded program control)
EXC_DOORBELL            = eapr.REG_IVOR36
EXC_DOORBELL_CRITICAL   = eapr.REG_IVOR37

# E.HV (embedded hypervisor)
EXC_GUEST_DOORBELL      = eapr.REG_IVOR38
EXC_GUEST_DOORBELL_CRITICAL = eapr.REG_IVOR39
EXC_HYPERCALL           = eapr.REG_IVOR40
EXC_HYPERPRIV           = eapr.REG_IVOR41

# E.HV.LRAT (embedded hypervisor logical to real address translation)
EXC_LRAT_ERROR          = eapr.REG_IVOR42

# MPC5674F INTC
MCR_HVEN = 0
MCR_VTES = 5

MCR_HVEN_MASK   = 1 << MCR_HVEN
MCR_VTES_MASK   = 1 << MCR_VTES

MMD_MCR = 0
MMD_CPR = 2
MMD_IACKR = 4
